name: test pull requests

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: use nodejs 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install dependencies
        run: yarn
      - name: run build
        run: yarn build
      - name: run tests
        run: yarn test
